- id: doi:10.1152/ajprenal.00035.2023
  type: paper
  description: Urothelial cells play a sensory role in bladder function. However, it has been particularly challenging to study this communication as both sensory neurons and urothelial cells express similar sensory receptors. Here we demonstrate using an optogenetic technique, that specific urothelial stimulation alone resulted in bladder contractions. This approach will have a long-lasting impact on how we study urothelial-to-sensory neuron communication and the changes that occur under disease conditions
  date: 2023-07-11
  image: https://journals.physiology.org/cms/10.1152/ajprenal.00035.2023/asset/images/medium/f-00035-2023r01.png
  buttons:
    - type: source
      text: Manuscript Source
      link: https://journals.physiology.org/doi/full/10.1152/ajprenal.00035.2023
    - type: website
      link: https://journals.physiology.org/doi/full/10.1152/ajprenal.00035.2023
  tags:
    - Urothelium
    - Sensory
  repo: greenelab/meta-review

- id: doi:10.7554/eLife.89767.3
  image: https://iiif.elifesciences.org/lax:89767%2Felife-89767-fig1-v1.tif/full/1234,/0/default.webp
  
- id: doi:10.1152/ajprenal.00204.2024
  image: https://journals.physiology.org/cms/10.1152/ajprenal.00204.2024/asset/images/medium/ajprenal.00204.2024r01.png

- id: doi:10.1038/s41467-025-55992-x
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-025-55992-x/MediaObjects/41467_2025_55992_Fig1_HTML.png?as=webp
